version: 0.2

phases:
  pre_build:
    commands:
      - echo Building Catagory Service
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - BUILD_ID=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building Maven Project
      - mvn clean
      - mvn install
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $SERVICE_NAME:$BUILD_ID --build-arg JAR_FILE=SkillTypeService-0.0.1-SNAPSHOT.jar --build-arg SPRING_ENV=$SPRING_ENV --build-arg DB_USER=$DB_USER --build-arg DB_PASS=$DB_PASS --build-arg DB_URL=$DB_URL .
      - docker tag $SERVICE_NAME:$BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE_NAME:$BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE_NAME:$BUILD_ID
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE_NAME:$BUILD_ID > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - 'Dockerfile'
    - 'target/SkillTypeService-0.0.1-SNAPSHOT.jar'