spring:
  application:
    name: skill
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create

eureka:
 client:
   service-url:
     default-zone: ${EUREKA_ZONE}

server:
  port: 8080
